USB_VID = 0x239A
USB_PID = 0x802A
USB_PRODUCT = "PCA10059"
USB_MANUFACTURER = "Nordic Semiconductor"
USB_HID_DEVICES = "FIDO"
# USB_DEVICES = "CDC,HID"
USB_DEVICES = "HID"

MCU_CHIP = nrf52840

INTERNAL_FLASH_FILESYSTEM = 1
